name: Add milestone based on label
on:
  issues:
    types: [labeled]
jobs:
  add-milestone-by:
    runs-on: ubuntu-latest
    name: Add milestone by label
    steps:
      -
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      -
        run: |
          echo 'hola'
